WINDOW_NAME = "OpenCV Fruit Ninja"

CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
TARGET_FPS = 60
MIRROR_CAMERA = True

HAND_LANDMARKER_MODEL_PATH = "work/models/hand_landmarker.task"
MENU_HOVER_SECONDS = 1.0

MAX_TRAIL_POINTS = 12
SLICE_SPEED_THRESHOLD = 18.0
SLICE_LINE_THICKNESS = 5
TRAIL_FADE_SECONDS = 0.22

SPAWN_INTERVAL_SECONDS = 1.0
GRAVITY = 0.42
FRUIT_RADIUS = 36
BOMB_RADIUS = 32
MAX_MISSES = 3
BOMB_CHANCE = 0.18
FREEZE_FRUIT_CHANCE = 0.12
GOLD_FRUIT_CHANCE = 0.08
FIRE_FRUIT_CHANCE = 0.08
SHOCK_FRUIT_CHANCE = 0.08
FREEZE_DURATION_SECONDS = 3.0
FROZEN_WORLD_SPEED = 0.45
FIRE_DURATION_SECONDS = 4.0
FIRE_SCORE_MULTIPLIER = 2.0
SHOCK_CHAIN_RADIUS_MULTIPLIER = 3.2

FRUIT_SCORE = 10
GOLD_FRUIT_SCORE = 35
FREEZE_FRUIT_SCORE = 18
FIRE_FRUIT_SCORE = 20
SHOCK_FRUIT_SCORE = 22
COMBO_RESET_SECONDS = 1.0
COMBO_POPUP_SECONDS = 0.7
POPUP_LIFETIME_SECONDS = 0.8
HIT_EFFECT_LIFETIME_SECONDS = 0.45
WAVE_BANNER_SECONDS = 1.4

FONT = 0
